todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/config/routes.rb
Rails.application.routes.draw do
  resources :destinations, only: :index

  resources :trips do
    resources :destinations
  end

  root to: 'trips#index'

end

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/models/destination.rb
class Destination < ActiveRecord::Base
	attr_accessible :description, :name

	belongs_to :trip

	validates_presence_of :name
end

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/models/trip.rb
class Trip < ActiveRecord::Base
	attr_accessible :description, :name

	has_many :destinations
	validates_presence_of :name
end

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  before_action :set_destination, only: [:show, :edit, :update, :destroy]

  # GET /destinations
  # GET /destinations.json
  def index
    @destinations = Destination.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @destinations }
    end
  end

  # GET /destinations/1
  # GET /destinations/1.json
  def show
    @trip = Trip.find(params[:trip_id])
    @destination = Destination.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @destination }
    end
  end

  # GET /destinations/new
  def new
    @trip = Trip.find(params[:trip_id])
    @destination = Destination.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @destination }
    end

  end

  # GET /destinations/1/edit
  def edit
    @trip = Trip.find(params[:trip_id])
    @destination = Destination.find(params[:id])
  end

  # POST /destinations
  # POST /destinations.json

  def create 
    @trip = Trip.find(params[:trip_id])
    @destination = @trip.destinations.new(params[:destination])

    respond_to do |format|
      if @destination.save
        format.html { redirect_to trip_destination_path(@trip, @destination), notice: 'Destination was successfully created.' }
        format.json { render :show, status: :created, location: @destination }
      else
        format.html { render :new }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /destinations/1
  # PATCH/PUT /destinations/1.json
  def update
    @destination = Destination.find(params[:id])
    @trip = @destination.trip
    
    respond_to do |format|
      if @destination.update_attributes(params[:destination])
        format.html { redirect_to trip_destination_path(@destination.trip, @destination), notice: 'Destination was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @destination.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /destinations/1
  # DELETE /destinations/1.json
  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy
    respond_to do |format|
      format.html { redirect_to destinations_url, notice: 'Destination was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_destination
      @destination = Destination.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def destination_params
      params.require(:destination).permit(:name, :description)
    end
end

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :set_trip, only: [:show, :edit, :update, :destroy]

  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to @trip, notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trips/1
  # PATCH/PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to @trip, notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trip
      @trip = Trip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def trip_params
      params.require(:trip).permit(:name, :description)
    end
end

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/helpers/destinations_helper.rb
module DestinationsHelper
end

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/helpers/trips_helper.rb
module TripsHelper
end

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/views/destinations/_form.html.erb
<%= form_for [@trip, @destination] do |f| %>
  <% if @destination.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@destination.errors.count, "error") %> prohibited this destination from being saved:</h2>

      <ul>
      <% @destination.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/views/destinations/edit.html.erb
<h1>Editing destination</h1>

<%= render 'form' %>

<%= link_to 'Show', trip_destination_path(@trip, @destination) %> |
<%= link_to 'Back', trip_path(@trip) %>

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/views/destinations/index.html.erb
<h1>Listing destinations</h1>

<table class="table">
  <tr>
    <th>Name</th>
    <th>Trip</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @destinations.each do |destination| %>
  <tr>
    <td><%= destination.name %></td>
    <td><%= destination.trip.name %></td>
    <td><%= destination.description %></td>
    <td><%= link_to 'Show', trip_destination_path(destination.trip, destination) %></td>
    <td><%= link_to 'Edit', edit_trip_destination_path(destination.trip, destination) %></td>
    <td><%= link_to 'Destroy', trip_destination_path(destination.trip, destination), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/views/destinations/new.html.erb
<h1>New destination</h1>

<%= render 'form' %>

<%= link_to 'Back', destinations_path %>

todos/rails/code_school/screencasts/rails_app_from_scratch_pt_1/wandrr/app/views/destinations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @destination.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @destination.description %>
</p>

<table class="table">
	<tr>
		<th>Destination</th>
		<th>Description</th>
	</tr>

	<% @trip.destinations.each do |destination| %>
		<tr>
			<td><%= destination.name %></td>
			<td><%= destination.description %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'Edit', edit_trip_destination_path(@trip, @destination) %> |
<%= link_to 'Back', trip_path(@trip) %>